name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  VERSION: 0.1.${{ github.run_number }}

jobs:
  build:
    runs-on: windows-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and Publish
        run: dotnet publish --configuration Release  -p:Version=${{ env.VERSION }} --self-contained --no-restore -o publish

      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: zip
          directory: publish
          filename: roguelike-${{ env.VERSION }}.zip
                
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          commit: master
          artifacts: publish/roguelike-${{ env.VERSION }}.zip
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}